parameters:
#    migol_user.example.class: Migol\UserBundle\Example

services:
#    migol_user.example:
#        class: %migol_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
