SlooContactsBundle:
    resource: "@SlooContactsBundle/Resources/config/routing.yml"
    prefix:   /social/sloo/

RIABackboneBundle:
    resource: "@RIABackboneBundle/Resources/config/routing.yml"
    prefix:   /

MigolBackendBundle:
    resource: "@MigolBackendBundle/Resources/config/routing.yml"
    prefix:   /admin/migol/

SlooBackendBundle:
    resource: "@SlooBackendBundle/Resources/config/routing.yml"
    prefix:   /admin/sloo/

StyleBootstrapFormBundle:
    resource: "@StyleBootstrapFormBundle/Resources/config/routing.yml"
    prefix:   /

MigolCommonPagesBundle:
    resource: "@MigolCommonPagesBundle/Resources/config/routing.yml"
    prefix:   /

StyleBootstrapBundle:
    resource: "@StyleBootstrapBundle/Resources/config/routing.yml"
    prefix:   /

MigolUserBundle:
    resource: "@MigolUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
