MigolCommonPagesBundle_homepage:
    pattern:  /
    defaults: { _controller: MigolCommonPagesBundle:Default:index }

MigolCommonPagesBundle_dashboard:
    pattern:  /social/dashboard
    defaults: { _controller: MigolCommonPagesBundle:Private:index }
