parameters:
#    migol_common_pages.example.class: Migol\CommonPagesBundle\Example

services:
#    migol_common_pages.example:
#        class: %migol_common_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
