parameters:
#    sloo_backend.example.class: Sloo\BackendBundle\Example

services:
#    sloo_backend.example:
#        class: %sloo_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
