<?php

namespace Sloo\BackendBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function findByNameLike($term)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c.id, c.name FROM SlooBackendBundle:City c WHERE c.name like '%".$term."%' ORDER BY c.name ASC")
            ->getArrayResult();
    }
}