<?php

namespace Sloo\BackendBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function listAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM SlooBackendBundle:Country c ORDER BY c.name ASC')
            ->getResult();
    }
    
}